---

rules:
  document-start: disable
  line-length:
    max: 120
    level: warning
  truthy: disable
 #FIXME: this is a hotfix for the .yaml pre-commit checks that fail on windows because of long lines
ignore: |
  .github/**/*.yml
