name: xhydro-dev
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  # Don't forget to sync changes between environment.yml, environment-dev.yml, and pyproject.toml!
  # Main packages
  - cartopy
  - geopandas
  - haversine >=2.8.1
  - leafmap
  - numpy <2.0.0
  - pandas >=2.2.0
  - planetary-computer
  - pystac
  - pystac-client
  - pooch >=1.8.0
  - pydantic >=2.0,<2.5.3  # FIXME: Remove pin once our dependencies (xclim, xscen) support pydantic 2.5.3
  - pyyaml
  - rasterio
  - ravenpy >=0.15.0
  - rioxarray
  - spotpy
  - stackstac >=0.5.1
  - statsmodels
  - tqdm
  - xarray >=2023.11.0
  - xarray-spatial
  - xclim >=0.48.2
  - xdatasets >=0.3.6
  - xscen >=0.8.3
  - xvec
  - pyjuliacall >=0.9.20
  # Dev tools and testing
  - pip >=24.0
  - blackdoc ==0.3.9
  - bump-my-version >=0.24.3
  - coverage >=7.5.0
  - coveralls >=4.0.0
  - flake8 >=7.1.0
  - flake8-rst-docstrings >=0.3.0
  - furo
  - ipykernel
  - ipython
  - isort ==5.13.2
  - jupyter_client
  - nbsphinx
  - nbval >=0.11.0
  # - numpydoc >=1.8.0  # latest version not yet available on conda-forge
  - pandoc
  - pooch >=1.8.0
  - pre-commit >=3.5.0
  - black ==24.4.2
  - ruff >=0.5.0
  - watchdog >=4.0.0
  - sphinx >=7.0.0
  - sphinx-autoapi
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-intl
  - sphinxcontrib-napoleon
  # Testing
  - pytest >=8.2.2
  - pytest-cov >=5.0.0
  - pytest-xdist >=3.2.0
  - tox >=4.16.0
  # Packaging
  - flit >=3.9.0,<4.0
  # Notebooks
  - hvplot
  - xagg
