name: xhydro
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  # Don't forget to sync changes between environment.yml, environment-dev.yml, and pyproject.toml!
  # Main packages
  - cartopy
  - geopandas
  - haversine
  - intake <2.0.0 # This should be set by xdatasets once on conda-forge
  - leafmap
  - numpy
  - pandas
  - planetary-computer
  - pooch >=1.8.0
  - pydantic >=2.0,<2.5.3  # FIXME: Remove pin once our dependencies (xclim, xscen) support pydantic 2.5.3
  - pystac
  - pystac-client
  - pyyaml
  - rasterio
  - spotpy
  - stackstac
  - statsmodels
  - tqdm
  - xarray >=2023.11.0
  - xclim >=0.48.2
  - xscen >=0.8.3
  - pip >=23.3.0
  - pyjuliacall
  - pip:
    - xdatasets >=0.3.5
    