name: xhydro
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  # Don't forget to sync changes between environment.yml, environment-dev.yml, and pyproject.toml!
  # Main packages
  - botocore == 1.34.106
  - aiobotocore == 2.13.0
  - cartopy
  - geopandas
  - haversine
  - leafmap
  - numpy <2.0.0
  - pandas
  - planetary-computer
  - pooch >=1.8.0
  - pydantic >=2.0,<2.5.3  # FIXME: Remove pin once our dependencies (xclim, xscen) support pydantic 2.5.3
  - pystac
  - pystac-client
  - pyyaml
  - rasterio
  - ravenpy >=0.15.0
  - rioxarray
  - spotpy
  - stackstac
  - statsmodels
  - tqdm
  - xarray >=2023.11.0
  - xarray-spatial
  - xclim >=0.48.2
  - xdatasets >=0.3.5
  - xscen >=0.8.3
  - xvec
  - pip >=23.3.0
