name: xhydro
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.13
  - pip >=24.2.0
  # Don't forget to sync changes between environment.yml, environment-dev.yml, and pyproject.toml!
  # Main packages
  - cartopy >=0.23.0
  - geopandas >=1.0
  - haversine >=2.8.1
  - importlib-metadata <8.0  # Required for xesmf >=8.4.0,<8.6 to work on Windows
  - leafmap
  - numpy >=1.23,<2.0.0
  - pandas >=2.2.0
  - planetary-computer
  - pooch >=1.8.0
  - pydantic >=2.0,<2.5.3  # FIXME: Remove pin once our dependencies (xclim, xscen) support pydantic 2.5.3
  - pystac
  - pystac-client
  - pyyaml >=6.0.2
  - rasterio <=1.3.11  # temporary pin until https://github.com/xarray-contrib/xvec/issues/85 is addressed.
  - ravenpy >=0.15.0
  - rioxarray >=0.15.0
  - spotpy >=1.6.2
  - stackstac >=0.5.1
  - statsmodels >=0.14.0
  - tqdm
  - xarray >=2023.11.0
  - xarray-spatial >=0.3.7
  - xclim >=0.48.2,<0.53
  - xdatasets >=0.3.6
  - xscen >=0.8.3
  - xvec
