name: xhydro-dev
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  # Don't forget to sync changes between environment.yml, environment-dev.yml, and pyproject.toml!
  # Main packages
  - cartopy
  - geopandas
  - haversine
  - leafmap
  - numpy <2.0.0
  - pandas
  - planetary-computer
  - pystac
  - pystac-client
  - pooch >=1.8.0
  - pydantic >=2.0,<2.5.3  # FIXME: Remove pin once our dependencies (xclim, xscen) support pydantic 2.5.3
  - pyyaml
  - rasterio
  - ravenpy >=0.15.0
  - rioxarray
  - spotpy
  - stackstac
  - statsmodels
  - tqdm
  - xarray >=2023.11.0
  - xarray-spatial
  - xclim >=0.48.2
  - xdatasets >=0.3.6
  - xscen >=0.8.3
  - xvec
  - pip >=23.3.0
  # Dev
  - black ==24.4.2
  - blackdoc ==0.3.9
  - bump-my-version >=0.18.3
  - coverage >=7.4.0
  - coveralls >=4.0.0
  - flake8 >=7.0.0
  - furo
  - ipykernel
  - ipython
  - isort ==5.13.2
  - jupyter_client
  - nbsphinx
  - nbval >=0.11.0
  - pandoc
  - pooch
  - pre-commit >=3.3.2
  - pytest >=7.3.1
  - pytest-cov >=5.0.0
  - ruff >=0.3.0
  - sphinx
  - sphinx-autoapi
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-intl
  - sphinxcontrib-napoleon
  # Testing
  - tox >=4.5.1
  # Packaging
  - flit >=3.9.0,<4.0
  # Notebooks
  - hvplot
  - xagg
